'use strict';
const fs = require('node:fs');
const path = require('node:path');
const yaml = require('js-yaml');
const root = path.resolve(__dirname, '..');
const normalizeLineEndings = value => value.replace(/\r\n/g, '\n');
const defaults = yaml.load(fs.readFileSync(path.join(root, '_config.yml'), 'utf8'));
const scopes = {
  brand: 'Header and metadata', home: 'Cover homepage', routes: 'Generated routes', navigation: 'Header navigation',
  pages: 'Generated pages', about: 'About page', listing: 'Blog, archives, categories and tags', post: 'Article pages',
  search: 'Local article search', footer: 'Footer', style: 'Site appearance', motion: 'Browser interactions',
  seo: 'Metadata and feed link', labels: 'Built-in UI text', custom: 'Site-authored extensions'
};
const descriptions = {
  'home.mode': 'cover generates a full-screen homepage; blog places the article index at the root.',
  'home.image': 'Static cover artwork. src is a site-relative or HTTP(S) URL; width/height are intrinsic dimensions.',
  'pages.custom': 'Ordered generated pages. An existing source page at the same route takes precedence.',
  'about.file': 'File relative to the blog source directory; takes precedence over about.content.',
  'about.header_html': 'Trusted HTML replacing the full About heading.',
  'about.sidebar_html': 'Trusted HTML replacing the default profile sidebar.',
  'about.profile.enabled': 'Shows the configured profile. To remove the sidebar column, also leave about.sidebar_html empty.',
  'post.comments': 'Shows custom.after_post. This switch does not install a comment provider.',
  'post.toc_depth': 'Maximum heading level shown in the article table of contents; integer from 1 to 6.',
  'search.path': 'Generated local search JSON path; respects the site root.',
  'search.limit': 'Maximum displayed search results; positive integer. Indexing remains local.',
  'seo.rss': 'URL of an existing feed generated by a separate plugin.',
  'style.variables': 'Extra CSS custom properties without the leading --. Keys must be CSS identifiers.',
  'labels': 'UI translation overrides. Empty strings remove optional server-rendered wording; keep browser feedback labels nonempty.',
  'custom.css': 'Ordered stylesheet URLs loaded after theme styles.',
  'custom.js': 'Ordered script URLs loaded with defer.',
  'custom.after_post': 'Trusted article-end HTML, controlled by the comments switch.',
  'about.profile.contacts': 'Ordered contacts. Empty entries are hidden; value-only entries are selectable text.'
};

const scopesZh = {
  brand: '页眉与元数据', home: '封面首页', routes: '生成页面的路由', navigation: '页眉导航',
  pages: '生成页面', about: 'About 页面', listing: '文章、归档、分类和标签列表', post: '文章页面',
  search: '本地文章搜索', footer: '页脚', style: '站点外观', motion: '浏览器交互',
  seo: '元数据与订阅链接', labels: '内置界面文字', custom: '站点自定义扩展'
};
const descriptionsZh = {
  'home.mode': 'cover 生成全屏封面；blog 将文章列表放在根目录。',
  'home.image': '静态封面图片。src 是站点相对路径或 HTTP(S) URL；width/height 是原始尺寸。',
  'pages.custom': '有序的自动生成页面列表；相同路由的源页面优先。',
  'about.file': '相对于博客 source 目录的文件，优先于 about.content。',
  'about.header_html': '替换整个 About 标题的可信 HTML。',
  'about.sidebar_html': '替换默认个人资料侧栏的可信 HTML。',
  'about.profile.enabled': '显示配置生成的个人资料；若要移除侧栏及其列，还需清空 about.sidebar_html。',
  'post.comments': '显示 custom.after_post；该开关不会安装评论服务。',
  'post.toc_depth': '文章目录中显示的最大标题级别，取 1 至 6 的整数。',
  'search.path': '生成的本地搜索 JSON 路径，遵循站点根路径。',
  'search.limit': '最多显示的搜索结果数，取正整数；索引保持本地生成。',
  'seo.rss': '由独立插件生成的现有订阅文件 URL。',
  'style.variables': '额外的 CSS 自定义属性，不含开头的 --；键名必须是 CSS 标识符。',
  'labels': '界面译文覆盖值；空字符串可移除构建时渲染的可选文字，浏览器交互提示请保留非空文字。',
  'custom.css': '有序样式表 URL，加载于主题样式之后。',
  'custom.js': '有序脚本 URL，以 defer 加载。',
  'custom.after_post': '受评论开关控制的可信文章末尾 HTML。',
  'about.profile.contacts': '有序联系方式，空条目隐藏；仅有 value 的条目显示为可选中文字。'
};

function schema(value, key = '') {
  const description = descriptions[key] || `${scopes[key.split('.')[0]] || 'Theme'}: ${key}. See the configuration guide for behavior.`;
  if (Array.isArray(value)) return { type: 'array', description, default: value, items: { type: 'object' } };
  if (value && typeof value === 'object') return { type: 'object', description, additionalProperties: !Object.keys(value).length, properties: Object.fromEntries(Object.entries(value).map(([name, child]) => [name, schema(child, key ? `${key}.${name}` : name)])) };
  return { type: typeof value, description, default: value };
}

const definition = { $schema: 'http://json-schema.org/draft-07/schema#', title: 'Cosmos theme overrides', ...schema(defaults) };
delete definition.description;
definition.properties.home.properties.mode.enum = ['cover', 'blog'];
definition.properties.post.properties.toc_depth = { ...definition.properties.post.properties.toc_depth, type: 'integer', minimum: 1, maximum: 6 };
definition.properties.search.properties.limit = { ...definition.properties.search.properties.limit, type: 'integer', minimum: 1 };
const link = { type: 'object', additionalProperties: false, properties: { route: { enum: ['home', 'about', 'blog', 'archives', 'categories', 'tags'] }, url: { type: 'string' }, label: { type: 'string' }, icon: { type: 'string' } }, anyOf: [{ required: ['route'] }, { required: ['url'] }] };
definition.properties.navigation.items = link;
definition.properties.home.properties.links.items = link;
definition.properties.footer.properties.links.items = link;
definition.properties.about.properties.profile.properties.facts.items = { type: 'object', properties: { label: { type: 'string' }, value: { type: 'string' } }, additionalProperties: false };
definition.properties.about.properties.profile.properties.contacts.items = { type: 'object', properties: Object.fromEntries(['label', 'url', 'value', 'icon'].map(key => [key, { type: 'string' }])), additionalProperties: false };
definition.properties.pages.properties.custom.items = { type: 'object', properties: { ...Object.fromEntries(['path', 'title', 'layout', 'content', 'file'].map(key => [key, { type: 'string' }])), enabled: { type: 'boolean' } }, required: ['path'], additionalProperties: true };
for (const type of ['css', 'js']) definition.properties.custom.properties[type].items = { type: 'string' };
definition.properties.labels.additionalProperties = { type: 'string' };
definition.properties.style.properties.variables.additionalProperties = { type: ['string', 'number'] };
for (const name of ['body_line_height', 'body_mobile_line_height', 'quote_line_height']) {
  definition.properties.style.properties.typography.properties[name].type = ['number', 'string'];
}

const rows = [];
function walk(value, prefix = '') {
  for (const [key, child] of Object.entries(value)) {
    const name = prefix ? prefix + '.' + key : key;
    if (child && typeof child === 'object' && !Array.isArray(child) && Object.keys(child).length) walk(child, name);
    else {
      const setting = name.split('.').reduce((node, key) => node.properties[key], definition);
      rows.push({ name, child, type: [setting.type].flat().join(' or ') });
    }
  }
}
walk(defaults);
const cell = value => String(value).replace(/\|/g, '\\|').replace(/\n/g, '<br>');
function reference(language) {
  const chinese = language === 'zh-CN';
  const descriptionsForLanguage = chinese ? descriptionsZh : descriptions;
  let result = '';
  for (const [group, scope] of Object.entries(chinese ? scopesZh : scopes)) {
    result += `### ${group} ${chinese ? '默认值' : 'defaults'}\n\n${chinese ? '作用范围' : 'Applies to'}: ${scope}.\n\n${chinese ? '| 配置项 | 类型 | 默认值 | 说明 |' : '| Setting | Type | Default | Notes |'}\n| --- | --- | --- | --- |\n`;
    for (const row of rows.filter(row => row.name === group || row.name.startsWith(group + '.'))) {
      const raw = JSON.stringify(row.child);
      const escaped = raw.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\|/g, '&#124;');
      const value = raw.length > 140 ? `<details><summary>${chinese ? '查看全部条目' : 'Show all entries'}</summary><code>${escaped}</code></details>` : '`' + cell(raw) + '`';
      const typesZh = { string: '字符串', boolean: '布尔值', number: '数字', integer: '整数', object: '对象', array: '列表', 'number or string': '数字或字符串' };
      result += `| \`${row.name}\` | ${chinese ? typesZh[row.type] : row.type} | ${value} | ${cell(descriptionsForLanguage[row.name] || '')} |\n`;
    }
    result += '\n';
  }
  return result;
}

const guides = ['en', 'zh-CN'].map(language => {
  const name = language === 'en' ? 'configuration.md' : 'configuration.zh-CN.md';
  const guide = normalizeLineEndings(fs.readFileSync(path.join(root, 'docs', name), 'utf8'));
  const marker = /<!-- cosmos:defaults:start -->[\s\S]*?<!-- cosmos:defaults:end -->/;
  if (!marker.test(guide)) throw new Error(`${name} is missing its defaults markers.`);
  return [name, guide.replace(marker, `<!-- cosmos:defaults:start -->\n\n${reference(language)}<!-- cosmos:defaults:end -->`)];
});

try {
  const Ajv = require('ajv');
  const validate = new Ajv({ strict: false }).compile(definition);
  const configs = ['_config.yml', 'examples/_config.cosmos.yml', ...fs.readdirSync(path.join(root, 'presets')).filter(name => name.endsWith('.yml')).map(name => 'presets/' + name)];
  for (const file of configs) {
    if (!validate(yaml.load(fs.readFileSync(path.join(root, file), 'utf8')))) throw new Error(`${file}: ${JSON.stringify(validate.errors)}`);
  }
  for (const [name, value] of [...guides, ['theme.schema.json', JSON.stringify(definition, null, 2) + '\n']]) {
    const target = path.join(root, 'docs', name);
    if (process.argv.includes('--check')) {
      if (!fs.existsSync(target) || normalizeLineEndings(fs.readFileSync(target, 'utf8')) !== value) throw new Error(`${name} is stale. Run npm run docs:reference.`);
    } else fs.writeFileSync(target, value);
  }
  console.log(`[Cosmos] Configuration reference and schema ${process.argv.includes('--check') ? 'are current' : 'generated'}.`);
} catch (error) { console.error(error.message); process.exitCode = 1; }
